### ISSUE TITLE
where's sorg.c?

### ISSUE THREAD

**Issue by greg-minshall** [PaulBatchelor/worgle#4]
glad to see this!  but, i just pulled, "make".

    {999} % make
    cc -Wall -std=c89 -pedantic -g -O3 -Iparg orgle.c -o orgle
    ./orgle worgle.org
    cc -Wall -std=c89 -pedantic -g -O3 -Iparg   -c -o parg/parg.o parg/parg.c
    cc -DWORGLITE -Wall -std=c89 -pedantic -g -O3 -Iparg worgle.c parg/parg.o -o worglite
    ./worglite -Werror -g db.org
    cc -Wall -std=c89 -pedantic -g -O3 -Iparg   -c -o db.o db.c
    cc -Wall -std=c89 -pedantic -g -O3 -Iparg   -c -o worgle.o worgle.c
    cc -Wall -std=c89 -pedantic -g -O3 -Iparg worgle.o db.o parg/parg.o -o worgle -lsqlite3
    make: *** No rule to make target 'sorg.c', needed by 'sorg'.  Stop.
    rm db.c

cheers!

**Comment by PaulBatchelor** [comment]
Wow. For whatever reason, it seems [sorg.org was accidentally removed](https://github.com/PaulBatchelor/worgle/commit/4c86aa70e8f30ae1ae4a3c64a75e4ad6888fe7b4). That's embarrassing. I brought it back, and things should work now.

**Comment by greg-minshall** [comment]
thanks!  btw, would you be open to a pull request or patch with mostly a usage message, -h (help), etc. (and, maybe adding a .gitignore)?  cheers!

**Comment by PaulBatchelor** [comment]
Feel free to add a .gitignore in a PR.

For the help message, would you mind filing a separate issue for that? It
is a great idea, but because Worgle is a literate program, it's something I
wouldn't mind discussing first.
